In [3]:
var1="gurpreet singh "
var2=" Balwant singh "
R=var1 + var2 +" how are you both"
R

'gurpreet singh  Balwant singh  how are you both'

In [4]:
type(R)

str

In [5]:
var3="gurpreet singh " + str(89)
var3

'gurpreet singh 89'

# f string and formate funcation 

In [21]:
var1="gurpreet singh "
var2=" Balwant singh "

string=f" my name is {var1} and my friends name is {var2 } "
string

' my name is gurpreet singh  and my friends name is  Balwant singh  '

In [22]:
type(string)

str

In [29]:
list="gurpreet singh"
print(list.lower())
print(list.upper())
# print(string.max())


gurpreet singh
GURPREET SINGH


# Funcation using into string

In [34]:
list="gurpreetsingh"
print(len(list))

13


In [36]:
list.count("r")

2

In [38]:
list.capitalize()

'Gurpreetsingh'

In [40]:
list.find("n")

10

In [41]:
list.replace("p","q")

'gurqreetsingh'

In [1]:
# most important funcation 
# 1)isalum()
# 2)isalpha()


list1="gurpreet singh is the best :"
list1.isalpha()
# list1.isalum()

False

In [13]:
list="12345657"
for char in list:
    print(char)

1
2
3
4
5
6
5
7


In [14]:
string="my name is gurpreet singh asnd so on :"
for item in string:
    print(item)

m
y
 
n
a
m
e
 
i
s
 
g
u
r
p
r
e
e
t
 
s
i
n
g
h
 
a
s
n
d
 
s
o
 
o
n
 
:


#  working on numpy module:
NumPy is a module for Python. The name is an acronym for "Numeric Python" or "Numerical Python". ... Furthermore, NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays.


In [6]:
import numpy as np
my_list=[1,2,3,4,5,6,7,8]
a=np.array(my_list)
type(a)
# 1d-2d-3d-4d------------nd

numpy.ndarray

In [7]:
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr1=np.arange(0,20,3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.random.randint(0,10)

8

In [14]:
np.random.randint(10,120,(4,4))

array([[ 35,  35,  15,  41],
       [ 66,  83,  75,  64],
       [ 26,  27,  40,  70],
       [101, 103,  82,  95]])

In [15]:
np.random.seed(101)
arr=np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [82]:
arr.max()
arr.min()
arr.mean()
arr.argmax() # it's gives the index
arr.argmin()

7

In [16]:
# reshape funcation=Gives a new shape to an array without changing its data.
#It is not always possible to change the shape of an array without copying the data. If you want an error to be raised when the data is copied,
#you should assign the new shape to the shape attribute of the array:

In [17]:
# in 1D and 2D array

my_string=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
my_string.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
my_string.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# in 2D(row) and 3D(column) array

my_string.reshape(2,3,2) # row*column*row
 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [20]:
# in 3D(row) and 4D(column) array
my_string.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
ar=np.arange(0,100)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
result=ar.reshape(10,10)
result

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
result[2,2]

22

In [25]:
result[8,8]

88

In [26]:
result[0:10,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [32]:
result[:,0] #intire row and 0 th column 
# result[0,:] # 0 th column and intire row
# result[0:3,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
result[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
result[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])