In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [5]:
data =pd.read_csv("MULTIPLE_ REGRESSION_ NASA01.csv")
data.head(10)

R&D   Administration  Marketing Spend     avrage        city      speed
0     1       165349.20        136897.80  471784.10    New York  192261.83
1     2       162597.70        151377.59  443898.53  California  191792.06
2     3       153441.51        101145.55  407934.54     Florida  191050.39
3     4       144372.41        118671.85  383199.62    New York  182901.99
4     5       142107.34         91391.77  366168.42     Florida  166187.94
5     6       131876.90         99814.71  362861.36    New York  156991.12
6     7       134615.46        147198.87  127716.82  California  156122.51
7     8       130298.13        145530.06  323876.68     Florida  155752.60
8     9       120542.52        148718.95  311613.29    New York  152211.77
9    10       123334.88        108679.17  304981.62  California  149759.96

In [11]:
real_x=data.iloc[:,1].values  # vector of one dimentional 
real_x=data.iloc[:,1:2].values
real_x

array([[165349.2 ],
       [162597.7 ],
       [153441.51],
       [144372.41],
       [142107.34],
       [131876.9 ],
       [134615.46],
       [130298.13],
       [120542.52],
       [123334.88],
       [101913.08],
       [100671.96],
       [ 93863.75],
       [ 91992.39],
       [119943.24],
       [114523.61],
       [ 78013.11],
       [ 94657.16],
       [ 91749.16],
       [ 86419.7 ],
       [ 76253.86],
       [ 78389.47],
       [ 73994.56],
       [ 67532.53],
       [ 77044.01],
       [ 64664.71],
       [ 75328.87],
       [ 72107.6 ],
       [ 66051.52],
       [ 65605.48],
       [ 61994.48],
       [ 61136.38],
       [ 63408.86],
       [ 55493.95],
       [ 46426.07],
       [ 46014.02],
       [ 28663.76],
       [ 44069.95],
       [ 20229.59],
       [ 38558.51],
       [ 28754.33],
       [ 27892.92],
       [ 23640.93],
       [ 15505.73],
       [ 22177.74],
       [  1000.23],
       [  1315.46],
       [     0.  ],
       [   542.05],
       [     0.  ]])

In [13]:
real_y=data.iloc[:,2].values 
real_y

array([136897.8 , 151377.59, 101145.55, 118671.85,  91391.77,  99814.71,
       147198.87, 145530.06, 148718.95, 108679.17, 110594.11,  91790.61,
       127320.38, 135495.07, 156547.42, 122616.84, 121597.55, 145077.58,
       114175.79, 153514.11, 113867.3 , 153773.43, 122782.75, 105751.03,
        99281.34, 139553.16, 144135.98, 127864.55, 182645.56, 153032.06,
       115641.28, 152701.92, 129219.61, 103057.49, 157693.92,  85047.44,
       127056.21,  51283.14,  65947.93,  82982.09, 118546.05,  84710.77,
        96189.63, 127382.3 , 154806.14, 124153.04, 115816.21, 135426.92,
        51743.15, 116983.8 ])

In [17]:
linear_regression=LinearRegression()
linear_regression.fit(real_x,real_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
polynomial_regression= PolynomialFeatures(degree=2)
real_x_poly=polynomial_regression.fit_transform(real_x)
real_x_poly

array([[1.00000000e+00, 1.65349200e+05, 2.73403579e+10],
       [1.00000000e+00, 1.62597700e+05, 2.64380120e+10],
       [1.00000000e+00, 1.53441510e+05, 2.35442970e+10],
       [1.00000000e+00, 1.44372410e+05, 2.08433928e+10],
       [1.00000000e+00, 1.42107340e+05, 2.01944961e+10],
       [1.00000000e+00, 1.31876900e+05, 1.73915168e+10],
       [1.00000000e+00, 1.34615460e+05, 1.81213221e+10],
       [1.00000000e+00, 1.30298130e+05, 1.69776027e+10],
       [1.00000000e+00, 1.20542520e+05, 1.45304991e+10],
       [1.00000000e+00, 1.23334880e+05, 1.52114926e+10],
       [1.00000000e+00, 1.01913080e+05, 1.03862759e+10],
       [1.00000000e+00, 1.00671960e+05, 1.01348435e+10],
       [1.00000000e+00, 9.38637500e+04, 8.81040356e+09],
       [1.00000000e+00, 9.19923900e+04, 8.46259982e+09],
       [1.00000000e+00, 1.19943240e+05, 1.43863808e+10],
       [1.00000000e+00, 1.14523610e+05, 1.31156572e+10],
       [1.00000000e+00, 7.80131100e+04, 6.08604533e+09],
       [1.00000000e+00, 9.46571

In [ ]:
# built  linear regression

In [ ]:
linear_regression2=LinearRegression()
linear_regression2.fit(real_x_poly)