In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("MULTIPLE_ REGRESSION_ NASA01.csv")
data.head(10)

R&D   Administration  Marketing Spend     avrage        city      speed
0     1       165349.20        136897.80  471784.10    New York  192261.83
1     2       162597.70        151377.59  443898.53  California  191792.06
2     3       153441.51        101145.55  407934.54     Florida  191050.39
3     4       144372.41        118671.85  383199.62    New York  182901.99
4     5       142107.34         91391.77  366168.42     Florida  166187.94
5     6       131876.90         99814.71  362861.36    New York  156991.12
6     7       134615.46        147198.87  127716.82  California  156122.51
7     8       130298.13        145530.06  323876.68     Florida  155752.60
8     9       120542.52        148718.95  311613.29    New York  152211.77
9    10       123334.88        108679.17  304981.62  California  149759.96

In [3]:

real_x=data.iloc[:,0:5].values    # generaliy loops moves from 0 index to till n-1
real_x

array([[1, 165349.2, 136897.8, 471784.1, 'New York'],
       [2, 162597.7, 151377.59, 443898.53, 'California'],
       [3, 153441.51, 101145.55, 407934.54, 'Florida'],
       [4, 144372.41, 118671.85, 383199.62, 'New York'],
       [5, 142107.34, 91391.77, 366168.42, 'Florida'],
       [6, 131876.9, 99814.71, 362861.36, 'New York'],
       [7, 134615.46, 147198.87, 127716.82, 'California'],
       [8, 130298.13, 145530.06, 323876.68, 'Florida'],
       [9, 120542.52, 148718.95, 311613.29, 'New York'],
       [10, 123334.88, 108679.17, 304981.62, 'California'],
       [11, 101913.08, 110594.11, 229160.95, 'Florida'],
       [12, 100671.96, 91790.61, 249744.55, 'California'],
       [13, 93863.75, 127320.38, 249839.44, 'Florida'],
       [14, 91992.39, 135495.07, 252664.93, 'California'],
       [15, 119943.24, 156547.42, 256512.92, 'Florida'],
       [16, 114523.61, 122616.84, 261776.23, 'New York'],
       [17, 78013.11, 121597.55, 264346.06, 'California'],
       [18, 94657.16, 145077

In [4]:
real_y=data.iloc[:,5].values
real_y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

# Multiple Linear Regression Part - 3 



In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()
real_x[:,4]=le.fit_transform(real_x[:,4])
real_x[:,4]


array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [8]:
# le=LabelEncoder()
# real_x[:,4]=le.fit_transform(real_x[:,4])
# oneHot=OneHotEncoder(categories=[3])
# real_x=oneHot.fit_transform(real_x).toarray()

ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [3])],
    remainder='passthrough' )        


real_x=ct.fit_transform(real_x)

# real_x
# real_x[:,4]

# Multiple Linear Regression Part - 3 

# Multiple Linear Regression Part - 4

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
traning_x,test_x,traning_y,test_y=train_test_split(real_x,real_y,test_size=0.2,random_state=0)

In [11]:
# traning_x
test_x

<10x52 sparse matrix of type '<class 'numpy.float64'>'
	with 49 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
MLR=LinearRegression()
MLR.fit(traning_x,traning_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
pred_y=MLR.predict(test_x)
pred_y

array([108414.75531443, 139857.70394673, 144359.62187205,  65016.89862016,
       175614.94388379, 108422.16935323,  66148.0516133 , 100064.27594278,
       115823.16686733, 167344.27353319])

In [15]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [16]:
MLR.coef_

array([-5.94902996e+03,  1.21544164e+04,  1.93733685e+03,  8.08574667e+03,
       -2.90632309e+04,  1.78252500e+03,  0.00000000e+00,  1.96629385e+03,
       -3.94893004e+03,  0.00000000e+00, -9.17215632e+03, -6.04839614e+03,
       -7.44221922e+02, -4.05160922e+03,  9.52063584e+03,  0.00000000e+00,
        9.24514715e+03,  9.78665154e+03,  0.00000000e+00,  1.61921889e+04,
        1.38147095e+04,  1.42494154e+04,  8.18359412e+03,  7.10049725e+03,
        0.00000000e+00,  0.00000000e+00,  1.99718113e+03, -2.85256251e+03,
       -1.60839211e+04, -1.30733044e+04,  1.04317348e+03, -8.90749424e+03,
       -3.84794269e+03, -2.58782130e+02,  2.15923087e+02, -1.12384527e+04,
        0.00000000e+00, -1.61492247e+03, -3.22845133e+03, -6.41827913e+03,
       -7.02156848e+03,  0.00000000e+00, -6.47992197e+03,  0.00000000e+00,
        9.94510119e+03,  0.00000000e+00,  7.68278114e+03,  5.09985922e+03,
       -1.59249638e+03,  3.75022605e-01,  8.56188718e-02,  8.34039038e+02])

In [17]:
MLR.intercept_

113354.39129527654

# Backward Elimination Part - 5


# cover up theory of back wards , we have forward elimination techniques but here discues about back wards elimination

# Backward Elimination Coding Part - 6

In [18]:
real_x=real_x[:,1:] # that is method to avoid dummy varible trape

In [19]:
print(real_x.shape,type(real_x), real_x.shape, type(real_x))

(50, 51) <class 'scipy.sparse.csr.csr_matrix'> (50, 51) <class 'scipy.sparse.csr.csr_matrix'>


In [20]:
real_x

<50x51 sparse matrix of type '<class 'numpy.float64'>'
	with 228 stored elements in Compressed Sparse Row format>

In [34]:
x_opt=real_x[:,[0,1,2,3,4,5]]

In [38]:
import statsmodels.api as sm

In [39]:
# ordinary list square error
reg_ols=sm.OLS(endog=real_y,exog=x_opt).fit()
# here endog is input values and exog is output values

ValueError: unrecognized data structures: <class 'numpy.ndarray'> / <class 'scipy.sparse.csr.csr_matrix'>

In [ ]:
y=b0+b1x1+b2x2+b3x3+b4x4----------BnXn